spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Knowledge_Fragment_Index?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/, classpath:/templates
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enabled: true


notion:
  secrets: secret_maPyFv5VNIS00RKJf36p4t9qmwo8m8YGZNAxhcC10Y5
  page-share-link: 1593df3a46e249f79749cc08490f6520